services:
  spring-kotlin-bff:
    container_name: spring-kotlin-bff
    build:
      context: .
      dockerfile: ./.setup/build/Dockerfile
    env_file:
      - .env
    restart: always
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - spring-kotlin-bff-network
    depends_on:
      - mongo-database
      - redis-cache
    volumes:
      - .:/usr/src/app

  mongo-database:
    image: mongo:8.0
    container_name: mongo-database
    env_file:
      - .env
    volumes:
      - "mongo-database:/data/db:delegated"
    ports:
      - "27017:27017"
    networks:
      - spring-kotlin-bff-network

  redis-cache:
    container_name: redis-cache
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - "redis-cache:/data"
    networks:
      - spring-kotlin-bff-network

networks:
  spring-kotlin-bff-network:
    external: true

volumes:
  mongo-database:
    driver: local
  redis-cache:
    driver: local
